### ISSUE TITLE
[Question] Can we separately fetch data that is not associated with the link?

### ISSUE THREAD

**Issue by AmmarSaleemG** [Owyn/CSS2RSS#1]
Can we separately fetch data that is not associated with the link, if Yes, How?

For example:
I want to fetch information about the job advertisements. 
Following is the part of the webpage on whose HTML source I am using your script to fetch whatever is in it right into my RssGuard Application.
![image](https://user-images.githubusercontent.com/15247707/174827921-f1314cc6-cb66-4127-ad08-2505e903e16f.png)
For now, there is No advertisement here and whenever I provide its HTML source, I get the following result:
![image](https://user-images.githubusercontent.com/15247707/174828528-e1e4eda0-e01f-4a88-a674-daeda9e18240.png)
It must be totally normal. But I want that text to be fetched which has no link.
i am using this code:
`python css2rss.py div.new-jobs`

**Comment by AmmarSaleemG** [comment]
Hmm, can this parser wrap a text into a link (a herf) or any other similar solution?

I still want to explain what i wish to have in this script, so please take a look at this picture.

![image](https://user-images.githubusercontent.com/15247707/174838697-886f6c9e-26d5-4cae-b452-e75e2c44c172.png)

I have tried my best to fetch the text "A" but it was not wrapped around the link or any element like `<u>`, etc, I failed to fetch it into my RSS application

**Comment by Owyn** [comment]
> Hmm, can this script wrap a text into a link (a herf) or any other similar solution?

It can't, It can't help you. It's not even the tool you need.
You're basically trying to watch videos using notepad and asking notepad developer to make it work for you. - No I can't do that, sorry.

> i was successfully able to fetch the text "Correct Option is:" because it was wrapped into <u> </u>.

" A" is wrapped into `span` together with the text above, see CSS selectors, you could specify that you want either 2nd child of span, or a child which is NOT `<u>`

**Comment by AmmarSaleemG** [comment]
Alright, thanks for your time.
