### ISSUE TITLE
OmegaScans (NSFW)

### ISSUE THREAD

**Issue by hercyle** [Owyn/CSS2RSS#11]
how will it be for the home page: 
```
https://omegascans.org/
```
and for a title: 
```
https://omegascans.org/series/delusional-diary
```

**Comment by Owyn** [comment]
I thought there were plenty of examples in the readme tho... 🔪

**Comment by hercyle** [comment]
i do play with it. and even ask chatgpt about it by supplying html code. yet, im unable to get it done.

**Comment by Owyn** [comment]
![image](https://github.com/user-attachments/assets/4972d11f-bb69-4a5c-8ffc-f6be66953838)

so like this, you click the link you want with "inspect", then look for the <a> link for it 
![image](https://github.com/user-attachments/assets/2c360758-bf82-4a6d-ac37-ca7630ad44ce)

it has `text-foreground` class on it, so the final css selector for such links would be `a.text-foreground`

and... that would have worked if the page wasn't constructed with javascript:
![image](https://github.com/user-attachments/assets/8f0710b0-f711-4148-8d29-1fe1a77f13ac)

cuz the page looks like this with javascript disabled: 
![image](https://github.com/user-attachments/assets/5b15ea28-6909-4403-bd73-f3ca1041096d)


but I think newer versions of RSSGuard (not lite ones) support scrapping pages with javascript, not sure

**Comment by hercyle** [comment]
what about the [home page](https://omegascans.org/)? the home page isnt javascript only

**Comment by Owyn** [comment]
the front page should work fine:

1st: find an element which holds all the items (chapters) for a series:
![image](https://github.com/user-attachments/assets/e4782061-f9ba-4183-bd52-76ae3f806d7d)
`div.flex-row` inside `div.grid`

then, fill the rest of the arguments (they are all the same here as on many other sites with the same design - e.g. reaperscans)
![image](https://github.com/user-attachments/assets/b041e214-b58f-48e3-bc3d-529fbf4cde65)
`python css2rss.py "@div.grid > div.flex-row" "h5" "img" "a[href*=chapter]" "span.text-xxs" "span.flex"`

or 
`python css2rss.py "@div.grid > div.flex-row" "h5" "img" ".pb-1 > a[href*=chapter]" "span.text-xxs" "span.flex"`
if we want to exclude premium chapters

**Comment by hercyle** [comment]
im having issues with `Maya`. im on archlinux and did installed maya through `pipx install maya --include-deps`
and i do get errors:
```
Traceback (most recent call last):
File "/home/user/.config/RSS Gugard 4/css2rss.py", line 170, in <module> import maya ModuleNotFoundError: No module named 'maya'
```
i had tried your command in a **downgraded** rssguard-lite 4.6.3 version, and it did work with the latest css2rss and an older version of [css2rss](https://github.com/Owyn/CSS2RSS/blob/b18ac98254f75c4ef501cdb79d398820fcca7f25/css2rss.py).
however, in rssguard 4.7.4 (latest) the errors previously mentioned, occur. and i cant fallback to an older [css2rss](https://github.com/Owyn/CSS2RSS/blob/b18ac98254f75c4ef501cdb79d398820fcca7f25/css2rss.py) because it tells me "Error: feed format not recognized"

**Comment by Owyn** [comment]
there is no need to go to an older css2rss, just don't use the 6th argument for it (item date) if you don't want to parse dates
e.g. 
`python css2rss.py "@div.grid > div.flex-row" "h5" "img" ".pb-1 > a[href*=chapter]" "span.text-xxs" "span.flex"`
turns to this:
`python css2rss.py "@div.grid > div.flex-row" "h5" "img" ".pb-1 > a[href*=chapter]" "span.text-xxs"`

but you should rather just fix maya module not being installed for your python version that rssguard is using

there are likely multiple versions of python installed in your system and you have installed maya module just for one of them your older rssguard version is using, not the latest one

**Comment by hercyle** [comment]
>there is no need to go to an older css2rss, just don't use the 6th argument for it (item date) if you don't want to parse dates (using maya module)

yeah, but dates are important. i'd like to have maya, but is neither in the AUR nor official repos. and i cant do a `pip` install since that would be very~ scary.

>but you should rather just fix maya module not being installed for your python version that rssguard is using
>there are likely multiple versions of python installed in your system and you have installed maya module just for one of them your older rssguard version is using, not the latest one
```md
$ python --version
Python 3.12.6

$ pipx list                        
venvs are in /home/user/.local/pipx/venvs 
apps are exposed on your $PATH at /home/user/.local/bin 
manual pages are exposed at /home/user/.local/share/man 
  package lightnovel-crawler 3.7.2, installed using Python 3.12.4 
   - lightnovel-crawler 
   - lncrawl
  package maya 0.6.1, installed using Python 3.12.6 
   - dateparser-download
```

**Comment by Owyn** [comment]
well, if it works in `rssguard-lite 4.6.3 version` but not in the newer one - again it sounds like an issue with rssguard you should probably ask there 🤷🏻‍♂️  I'm not really a linux \ rssguard expert

**Comment by hercyle** [comment]
btw, this one didnt work either. `python css2rss.py "@div.grid > div.flex-row" "h5" "img" ".pb-1 > a[href*=chapter]" "span.text-xxs"` it throws me an `Error: feed format not recognized`

**Comment by Owyn** [comment]
that sounds like you inputted it somewhere wrong since there is no screenshot with this error

**Comment by hercyle** [comment]
no. i did input it fine. but i dunno anymore, i just downloaded the main.zip file and decided to drop it in rssguard folder and now it works after after removing `"span.flex"` which triggers maya errors.

btw, isnt it just better to stick with a different maya alternative? there should be others which have way more recognition and are way better supported by major distros like fedora/debian/archlinux?
