### ISSUE TITLE
Linux Mint and Python

### ISSUE THREAD

**Issue by Cronos-lab** [Owyn/CSS2RSS#5]
Hello,
I use this beautiful script since one year with Windows.

I'd like to use it with Linux (Linux Mint) from now on, but I have a small problem.

When I want to use a feed and the script, I get an error in RSS Guard :

`Status: error (The script returned an error: 'Traceback (most recent call last): File "/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/css2rss.py", line 8, in from bs4 import BeautifulSoup ModuleNotFoundError: No module named 'bs4'')`

The script "css2rss.py", is located here :
/home/user/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4

If I do pip3 list in the terminal, I get the bs4 module. I don't understand.

It is therefore impossible for me to generate new articles.

Thank you so much.

**Comment by Owyn** [comment]
Even on windows Python environment can be a total mess, I could only get it to work right with Chocolatey,

This usually happens when there are two or more versions of Python in the system somehow - you install modules for one and run the program with the 2nd...

Try uninstalling every python first then making sure .py scripts don't launch anymore - then installing a fresh python with a packet manager like Chocolatey

**Comment by martinrotter** [comment]
Do you actually have the module installed?

> pip install BeautifulSoup4

**Comment by Owyn** [comment]
try `pip install beautifulsoup4` instead of pip3

**Comment by Owyn** [comment]
> To run python you need a terminal. To open one you could for example just open the start menu and type 'terminal', then open one of the suggested programs. Once you have your terminal you need to call the program and give it some arguments to run with, in this case python

**Comment by Owyn** [comment]
> Rss Guard is installed from a Flatpak version because it is the most recent version.

I mean, what's the feed properties where css2rss is called?
is it python css2rss or python3 css2rss ? try both, I really dunno

**Comment by martinrotter** [comment]
You have to run it like this:

`python -c 'import bs4'`

**Comment by martinrotter** [comment]
It is very likely that the actual "python" you ran now in cmd is different "python" which runs in RSS Guard.

Try to use absolute path to "python" binaries in both cases. There is really not other magic in RSS Guard. It simply runs the binary with arguments.

**Comment by martinrotter** [comment]
Yes, flatpak version is sandboxed

Dne so 10. 2. 2024 11:22 uživatel Cronos ***@***.***> napsal:
