### ISSUE TITLE
need help with appending images to items' description

### ISSUE THREAD

**Issue by seventyiris83** [Owyn/CSS2RSS#8]
hello, i recently found css2rss and it is awesome 😊 i want to append rumble video thumbnails from this channel: https://rumble.com/c/LofiGirl into the items' descriptions. i tried  `img.thumbnail__image`, `div.thumbnail__thumb` and `thumbnail__grid--item` with the item description selector but the video thumbnails don't get appended to the items in rss guard 😞

i hope you can help me with this, ty :blush:

**Comment by Owyn** [comment]
`img.thumbnail__image` should work, it's just that it must be a child element of the 1st `item` you select in rss, so you'll have to select a new `item` which is parent to both the item's link and the image

**Comment by seventyiris83** [comment]
> `img.thumbnail__image` should work,

it doesn't 😞 

> it's just that it must be a child element of the 1st `item` you select in rss (because it is searched there inside `item`), so you'll have to select a new `item` which is a parent to both the item's link and the image

yeah, here though i'm not seeing any other item that contains the thumbnails of videos so i don't know. 

on this rumble channel: https://rumble.com/c/LofiGirl from the `img` element of `div class thumbnail__thumb` item of a video, rss guard grabs `this.src=&quot;data:image/svg+xml,%3Csvg width=` as article description instead of just `src` which has the thumbnail jpg url (https://hugh.cdn.rumble.cloud/s/s8/1/9/V/p/w/9Vpwf.oq1b.3-small-lofi-hip-hop-radio-beats-to.jpg)

if you try, can you get it to work?

**Comment by Owyn** [comment]
![image](https://github.com/user-attachments/assets/7e859a44-c334-47c9-abb0-da30e45f63e8)

Works fine for me
![image](https://github.com/user-attachments/assets/0cdf92c1-8227-40e1-95a1-e2459b06cf6a)
![image](https://github.com/user-attachments/assets/adcc7830-5ced-48c3-bc1d-aee4c96903c1)

**Comment by seventyiris83** [comment]
tried `python css2rss.py "[role='listitem']" "h3" "img"` like you put in the post processing script box

![0001](https://github.com/user-attachments/assets/cc045031-32c9-45b3-939e-5fd8f9431312)

and i still get the same result 😞 

![000001](https://github.com/user-attachments/assets/a9a602df-b3ba-4490-982b-242b380e4f14)

im running the latest css2rss and 4.7.2 lite. what version of rss guard are you running?

**Comment by Owyn** [comment]
> what version of rss guard are you running?

4.3.3

Perhaps it's a bug in the latest RSSGuard version, would be nice if you could report it so it could get fixed https://github.com/martinrotter/rssguard/issues

**Comment by seventyiris83** [comment]
> > what version of rss guard are you running?
> 
> 4.3.3
> 
> Perhaps it's a bug in the latest RSSGuard version, I remember there were some changing in the image parsing there... would be nice if you could report it so it could get fixed https://github.com/martinrotter/rssguard/issues

tested on 4.3.3 lite and it works. i'll report the problem

**Comment by seventyiris83** [comment]
see [comment](https://github.com/martinrotter/rssguard/issues/1477#issuecomment-2298225327)
